// This file is generated by scripts/generate-personnage-narratives.mjs.
// Do not edit it manually.

import type { ComponentType } from 'react';
import type { MDXComponents } from 'mdx/types';

export type PersonnageNarrativeComponent = ComponentType<{ components?: MDXComponents }>;
export type PersonnageNarrativeLoader = () => Promise<PersonnageNarrativeComponent>;

export const personnageNarrativeLoaders: Record<string, PersonnageNarrativeLoader> = {
  'amara-mere-douleurs': async () => (await import('@/content/personnages/amara-mere-douleurs/histoire.mdx')).default as PersonnageNarrativeComponent,
  'aurelia-reine-midas': async () => (await import('@/content/personnages/aurelia-reine-midas/histoire.mdx')).default as PersonnageNarrativeComponent,
  'elias-pilier-sacre': async () => (await import('@/content/personnages/elias-pilier-sacre/histoire.mdx')).default as PersonnageNarrativeComponent,
  'kael-eclipse': async () => (await import('@/content/personnages/kael-eclipse/histoire.mdx')).default as PersonnageNarrativeComponent,
  'prototype-technique': async () => (await import('@/content/personnages/prototype-technique/histoire.mdx')).default as PersonnageNarrativeComponent,
  'soryn-la-voilee': async () => (await import('@/content/personnages/soryn-la-voilee/histoire.mdx')).default as PersonnageNarrativeComponent,
  'varros-fleau': async () => (await import('@/content/personnages/varros-fleau/histoire.mdx')).default as PersonnageNarrativeComponent,
  'ysolde-sauvage': async () => (await import('@/content/personnages/ysolde-sauvage/histoire.mdx')).default as PersonnageNarrativeComponent,
};

export async function loadPersonnageNarrative(slug: string): Promise<PersonnageNarrativeComponent | null> {
  const loader = personnageNarrativeLoaders[slug];

  return loader ? loader() : null;
}
