// This file is generated by scripts/generate-personnage-narratives.mjs.
// Do not edit it manually.

import type { ComponentType } from 'react';
import type { MDXComponents } from 'mdx/types';

export type PersonnageNarrativeComponent = ComponentType<{ components?: MDXComponents }>;
export type PersonnageNarrativeLoader = () => Promise<PersonnageNarrativeComponent>;

export const personnageNarrativeLoaders: Record<string, PersonnageNarrativeLoader> = {
  'kael-eclipse': async () => (await import('@/content/personnages/kael-eclipse/histoire.mdx')).default as PersonnageNarrativeComponent,
  'prototype-technique': async () => (await import('@/content/personnages/prototype-technique/histoire.mdx')).default as PersonnageNarrativeComponent,
  'varros-fleau': async () => (await import('@/content/personnages/varros-fleau/histoire.mdx')).default as PersonnageNarrativeComponent,
};

export async function loadPersonnageNarrative(slug: string): Promise<PersonnageNarrativeComponent | null> {
  const loader = personnageNarrativeLoaders[slug];

  return loader ? loader() : null;
}
