// This file is generated by scripts/generate-personnage-narratives.mjs.
// Do not edit it manually.

import type { ComponentType } from 'react';
import type { MDXComponents } from 'mdx/types';

export type FactionNarrativeComponent = ComponentType<{ components?: MDXComponents }>;
export type FactionNarrativeLoader = () => Promise<FactionNarrativeComponent>;

export const factionNarrativeLoaders: Record<string, FactionNarrativeLoader> = {
  'ordre-de-l-arquet': async () => (await import('@/content/factions/ordre-de-l-arquet/histoire.mdx')).default as FactionNarrativeComponent,
};

export async function loadFactionNarrative(slug: string): Promise<FactionNarrativeComponent | null> {
  const loader = factionNarrativeLoaders[slug];

  return loader ? loader() : null;
}
